accessions_source_column_mappings: dict[str, str] = {
    "ID": "idno",
    "Description": "description",
    "Date of Donation": "donation_date",
    "Legacy ID-UMD": "legacy_idno_umd",
    "Donor Name (Form Entry)": "donor_name",
    "Donor Name (Linked)": "linked_entity_array",
    "Files": "file_array",
    "Donation Grouping Title": "title",
    "# Files": "file_count",
    "LDT Check (Temp)": "_ldt_check",
    "airtable_createdTime": "airtable_created_time",
    "airtable_id": "airtable_idno",
}

items_source_column_mappings: dict[str, str] = {
    "ID": "idno",
    "Accession": "linked_accessions_array",
    "File Count": "file_count",
    "Files": "linked_files_array",
    "airtable_createdTime": "airtable_created_time",
    "airtable_id": "airtable_idno",
}

entities_source_column_mappings: dict[str, str] = {
    "Name": "name",
    "Biography/History": "bio_hist",
    "Notes": "notes",
    "Entity Category": "category",
    "Alternate Name": "alt_name",
    "Address": "address",
    "Date of Birth": "date_of_birth",
    "Date of Death": "date_of_death",
    "Latitude": "latitude",
    "Authority Relationships": "auth_relations",
    "Authority Relationships 2": "auth_relations_2",
    "Linked Oral Histories (Interviewees)": "linked_to_oral_history",
    "Linked Digital Objects (to Place)": "linked_to_place",
    "Longitude": "longitude",
    "Linked Digital Objects (Creators)": "linked_as_creator",
    "Linked Digital Objects (as Recipients)": "linked_as_recipient",
    "Linked Digital Objects (to Signatories)": "linked_as_signatory",
    "Source Code": "lchp_source_code",
    "Linked Digital Objects (Source)": "linked_as_source",
    "Items": "linked_items_generic",
    "Linked Items (EntityAsSubject)": "linked_items_array",
    "airtable_createdTime": "airtable_created_time",
    "airtable_id": "airtable_idno",
}